name: Publish
on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Install and Build 🔧
        run: |
          yarn install
          yarn test
          yarn build
      - name: Deploy version
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          commit-message: 'CI: bumps version to {{version}} [skip ci]'
      - name: Publish
        run: npm config set_authToken=${{ secrets.ACCESS_TOKEN }} && npm publish

