name: Publish
on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Install and Build 🔧
        run: |
          yarn install
          yarn test
          yarn build
      - name: Deploy version
        uses: mikeal/merge-release@master
        id: deploy
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - run: git config --global user.email $(git --no-pager show -s --format='%ae' HEAD)
      - run: git config --global user.name $(git --no-pager show -s --format='%an' HEAD)
      - name: Commit new version
        run: |
          last_tag=$(git describe --tags --abbrev=0)
          npm version $last_tag --no-git-tag-version
          git add package.json
          git commit -m "[skip ci] bump version"
          git push
